name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
      - closed
      - assigned
env:
  PROJECT_NAME: test
jobs:
  issue_labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      repository-projects: write
    steps:
      - name: Add initial labels
        if: github.event.action == 'opened'
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "backlog"
          remove-labels: "inprogress, close"
          repo-token: ${{ secrets.KEY }}
          ignore-if-assigned: true

      - name: Set priority label
        if: github.event.action == 'opened'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.KEY }}
          script: |
            const body = context.payload.issue.body;
            if (body.includes('Daily（毎日対応）')) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['priority:daily']
              });
            } else if (body.includes('Weekly（週次対応）')) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['priority:weekly']
              });
            }

      - name: Add inprogress label
        if: github.event.action == 'assigned' || github.event.action == 'reopened'
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "inprogress"
          remove-labels: "backlog, close"
          repo-token: ${{ secrets.KEY }}
          ignore-if-assigned: true

      - name: Add close label
        if: github.event.action == 'closed'
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "close"
          remove-labels: "inprogress, backlog"
          repo-token: ${{ secrets.KEY }}
          ignore-if-assigned: true

  assign_issue_to_project:
    name: Assign issues to project
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: write
    steps:
      - name: Assign issues to project
        uses: technote-space/create-project-card-action@v1
        if: github.event.action == 'opened'
        with:
          PROJECT: "test"
          COLUMN: Backlog
          GITHUB_TOKEN: ${{ secrets.KEY }}

  move_assigned_card:
    runs-on: ubuntu-latest
    name: Move assigned card
    permissions:
      issues: write
      repository-projects: write
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        if: github.event.action == 'assigned'
        with:
          project: "test"
          column: In Progress
          repo-token: ${{ secrets.KEY }}

      - uses: alex-page/github-project-automation-plus@v0.3.0
        if: github.event.action == 'reopened'
        with:
          project: "test"
          column: In Progress
          repo-token: ${{ secrets.KEY }}
